################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../client_app.c \
../dcd.c \
../gatt_db.c \
../init_app.c \
../init_board_efr32xg2.c \
../init_mcu_efr32xg2.c \
../main.c \
../pti.c \
../retargetio.c \
../retargetserial.c 

OBJS += \
./client_app.o \
./dcd.o \
./gatt_db.o \
./init_app.o \
./init_board_efr32xg2.o \
./init_mcu_efr32xg2.o \
./main.o \
./pti.o \
./retargetio.o \
./retargetserial.o 

C_DEPS += \
./client_app.d \
./dcd.d \
./gatt_db.d \
./init_app.d \
./init_board_efr32xg2.d \
./init_mcu_efr32xg2.d \
./main.d \
./pti.d \
./retargetio.d \
./retargetserial.d 


# Each subdirectory must supply rules for building sources it contributes
client_app.o: ../client_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"client_app.d" -MT"client_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

dcd.o: ../dcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"dcd.d" -MT"dcd.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: ../gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: ../init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board_efr32xg2.o: ../init_board_efr32xg2.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"init_board_efr32xg2.d" -MT"init_board_efr32xg2.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu_efr32xg2.o: ../init_mcu_efr32xg2.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"init_mcu_efr32xg2.d" -MT"init_mcu_efr32xg2.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pti.o: ../pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"pti.d" -MT"pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

retargetio.o: ../retargetio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"retargetio.d" -MT"retargetio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

retargetserial.o: ../retargetserial.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-D__STACK_SIZE=0x1000' '-D__HEAP_SIZE=0x1200' '-DNVM3_DEFAULT_NVM_SIZE=24576' '-DMESH_LIB_NATIVE=1' '-DHAL_CONFIG=1' '-DEFR32MG21A020F1024IM32=1' -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/soc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/EFR32MG21_BRD4180A/config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/bsp" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/inc/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/CMSIS/Include" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/halconfig" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emlib/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/protocol/bluetooth/bt_mesh/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/chip/efr32/efr32xg2x" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/nvm3/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/common" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/hardware/kit/common/drivers" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/uartdrv/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/bootloader/api" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/common/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ble" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/sleep/src" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/emdrv/gpiointerrupt/inc" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/Device/SiliconLabs/EFR32MG21/Source/GCC" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/radio/rail_lib/protocol/ieee802154" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor/platform/halconfig/inc/hal-config" -I"/Users/clfilho/SimplicityStudio/BLEMesh/btmeshVendor" -Os -fno-builtin -flto -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=hard -MMD -MP -MF"retargetserial.d" -MT"retargetserial.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


